### ISSUE TITLE
A little help if it's possible

### ISSUE THREAD

**Issue by striff** [driftyco/ionic-image-gallery-app#4]
Can someone guide me on how to implement a Next/Previous button or a way to use those gestures already present in the code, to swipe left / right trough the array of images?

Thank you in advance!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](forum.ionicframework.com). Thanks for using Ionic!
